version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - collab-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/collab-docs
    depends_on:
      - mongo
    networks:
      - collab-net

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - collab-net

volumes:
  mongo-data:

networks:
  collab-net: